// src/data.js

const appointments = [
  {
    id: 1,
    date: "July 25, 2025",
    time: "10:00 AM",
    doctor: "Dr. El Hadi Zaid",
    location: "Ibn Sina Hospital",
    status: "Upcoming",
  },
  {
    id: 2,
    date: "June 15, 2025",
    time: "09:00 AM",
    doctor: "Dr. Chaouni Mouad",
    location: "CHU Fès",
    status: "Done",
  },
  {
    id: 3,
    date: "May 05, 2025",
    time: "04:30 PM",
    doctor: "Dr. Beniken Brahim",
    location: "Cheikh Zaid Clinic",
    status: "Done",
  },
  {
    id: 4,
    date: "June 12, 2024",
    time: "09:15 AM",
    doctor: "Dr. Ezzhar Said",
    location: "Clinique Al Amal",
    status: "Missed",
  },
  {
    id: 5,
    date: "August 01, 2025",
    time: "11:00 AM",
    doctor: "Dr. Fatima Lahlou",
    location: "MedVilla Health Center",
    status: "Upcoming",
  },

  {
    id: 1,
    date: "July 25, 2025",
    time: "10:00 AM",
    doctor: "Dr. El Hadi Zaid",
    location: "Ibn Sina Hospital",
    status: "Upcoming",
  },
  {
    id: 2,
    date: "June 15, 2025",
    time: "09:00 AM",
    doctor: "Dr. Chaouni Mouad",
    location: "CHU Fès",
    status: "Done",
  },
  {
    id: 3,
    date: "May 05, 2025",
    time: "04:30 PM",
    doctor: "Dr. Beniken Brahim",
    location: "Cheikh Zaid Clinic",
    status: "Done",
  },
  {
    id: 4,
    date: "June 12, 2024",
    time: "09:15 AM",
    doctor: "Dr. Ezzhar Said",
    location: "Clinique Al Amal",
    status: "Missed",
  },
  {
    id: 5,
    date: "August 01, 2025",
    time: "11:00 AM",
    doctor: "Dr. Fatima Lahlou",
    location: "MedVilla Health Center",
    status: "Upcoming",
  },
  {
    id: 1,
    date: "July 25, 2025",
    time: "10:00 AM",
    doctor: "Dr. El Hadi Zaid",
    location: "Ibn Sina Hospital",
    status: "Upcoming",
  },
  {
    id: 2,
    date: "June 15, 2025",
    time: "09:00 AM",
    doctor: "Dr. Chaouni Mouad",
    location: "CHU Fès",
    status: "Done",
  },
  {
    id: 3,
    date: "May 05, 2025",
    time: "04:30 PM",
    doctor: "Dr. Beniken Brahim",
    location: "Cheikh Zaid Clinic",
    status: "Done",
  },
  {
    id: 4,
    date: "June 12, 2024",
    time: "09:15 AM",
    doctor: "Dr. Ezzhar Said",
    location: "Clinique Al Amal",
    status: "Missed",
  },
  {
    id: 5,
    date: "August 01, 2025",
    time: "11:00 AM",
    doctor: "Dr. Fatima Lahlou",
    location: "MedVilla Health Center",
    status: "Upcoming",
  },

  {
    id: 1,
    date: "July 25, 2025",
    time: "10:00 AM",
    doctor: "Dr. El Hadi Zaid",
    location: "Ibn Sina Hospital",
    status: "Upcoming",
  },
  {
    id: 2,
    date: "June 15, 2025",
    time: "09:00 AM",
    doctor: "Dr. Chaouni Mouad",
    location: "CHU Fès",
    status: "Done",
  },
  {
    id: 3,
    date: "May 05, 2025",
    time: "04:30 PM",
    doctor: "Dr. Beniken Brahim",
    location: "Cheikh Zaid Clinic",
    status: "Done",
  },
  {
    id: 4,
    date: "June 12, 2024",
    time: "09:15 AM",
    doctor: "Dr. Ezzhar Said",
    location: "Clinique Al Amal",
    status: "Missed",
  },
  {
    id: 5,
    date: "August 01, 2025",
    time: "11:00 AM",
    doctor: "Dr. Fatima Lahlou",
    location: "MedVilla Health Center",
    status: "Upcoming",
  },
  {
    id: 1,
    date: "July 25, 2025",
    time: "10:00 AM",
    doctor: "Dr. El Hadi Zaid",
    location: "Ibn Sina Hospital",
    status: "Upcoming",
  },
  {
    id: 2,
    date: "June 15, 2025",
    time: "09:00 AM",
    doctor: "Dr. Chaouni Mouad",
    location: "CHU Fès",
    status: "Done",
  },
  {
    id: 3,
    date: "May 05, 2025",
    time: "04:30 PM",
    doctor: "Dr. Beniken Brahim",
    location: "Cheikh Zaid Clinic",
    status: "Done",
  },
  {
    id: 4,
    date: "June 12, 2024",
    time: "09:15 AM",
    doctor: "Dr. Ezzhar Said",
    location: "Clinique Al Amal",
    status: "Missed",
  },
  {
    id: 5,
    date: "August 01, 2025",
    time: "11:00 AM",
    doctor: "Dr. Fatima Lahlou",
    location: "MedVilla Health Center",
    status: "Upcoming",
  },

  {
    id: 1,
    date: "July 25, 2025",
    time: "10:00 AM",
    doctor: "Dr. El Hadi Zaid",
    location: "Ibn Sina Hospital",
    status: "Upcoming",
  },
  {
    id: 2,
    date: "June 15, 2025",
    time: "09:00 AM",
    doctor: "Dr. Chaouni Mouad",
    location: "CHU Fès",
    status: "Done",
  },
  {
    id: 3,
    date: "May 05, 2025",
    time: "04:30 PM",
    doctor: "Dr. Beniken Brahim",
    location: "Cheikh Zaid Clinic",
    status: "Done",
  },
  {
    id: 4,
    date: "June 12, 2024",
    time: "09:15 AM",
    doctor: "Dr. Ezzhar Said",
    location: "Clinique Al Amal",
    status: "Missed",
  },
  {
    id: 5,
    date: "August 01, 2025",
    time: "11:00 AM",
    doctor: "Dr. Fatima Lahlou",
    location: "MedVilla Health Center",
    status: "Upcoming",
  },
];

export { appointments };
